# Generated by Django 5.1.6 on 2026-03-12 21:50

import bookings.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('salons', '0005_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='salons.employee'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to=bookings.models.payment_upload_path),
        ),
    ]
