# Generated by Django 5.1.6 on 2026-03-12 20:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='salon',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='salon',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Optional manual rating shown in the UI (0.0-5.0).', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='salon',
            name='working_hours',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='SalonPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='salon_gallery/%Y/%m/')),
                ('caption', models.CharField(blank=True, default='', max_length=150)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='salons.salon')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
