# Generated by Django 5.1.6 on 2026-03-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0003_salon_email_salon_phone_number_salon_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='category',
            field=models.CharField(choices=[('hair', 'Hair'), ('nails', 'Nails'), ('makeup', 'Makeup'), ('skincare', 'Skincare'), ('spa', 'Spa')], default='hair', max_length=20),
        ),
    ]
